[workspace]

members = ["asap-data"] # ,"asap-embed","asap-network","asap-select", ,"asap-vae"
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5.20", features = ["derive"] }
flate2 = "1.0.34"

num_cpus = "1.16.0"
rayon = "1.10.0"
hdf5 = { package = "hdf5-metno", version = "0.9", features = ["blosc"] }
hdf5-sys = { package = "hdf5-metno-sys", version = "0.9", features = ["static", "zlib", "threadsafe"] }
libz-sys = { version = "1", features = ["libc"], default-features = false }
tempfile = "3.2"
rand = "0.8.5"

zarrs = { version = "0.17.1", features = ["gzip"] }
serde_json = "1.0"
serde = "1.0.214"

