[workspace]

members = ["asap-data", "asap-embed"] # ,"asap-network","asap-select", ,"asap-vae"
resolver = "2"

[workspace.dependencies]

asap-data = { path = "asap-data"} 
asap-embed = { path = "asap-embed" }
