[package]
name = "candle-util"
version = "0.1.0"
edition = "2021"

[dependencies]

asap-data = { path = "../asap-data" }
matrix-util = { path = "../matrix-util" }

anyhow = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
num_cpus = { workspace = true }
rayon = { workspace = true }
tempfile = { workspace = true }
rand = { workspace = true }
ndarray = { workspace = true }
ndarray-rand = { workspace = true }
rand_distr = { workspace = true }
nalgebra = { workspace = true }
nalgebra-sparse = { workspace = true }
approx = { workspace = true }

instant-distance = { workspace = true }
special = { workspace = true }
indicatif = { workspace = true }
log = "0.4"
env_logger = "0.11"

[target.'cfg(target_os = "linux")'.dependencies]
candle-core = { version = "^0.8", features = ["cuda","cudarc","cudnn"] }
candle-nn = { version = "^0.8", features = ["cuda"] }

[target.'cfg(target_os = "macos")'.dependencies]
candle-core = { version = "^0.8", features = ["metal","accelerate"] }
candle-nn = { version = "^0.8", features = ["metal","accelerate"] }

[dev-dependencies]
textplots = { version = "0.8" }
